// flow-typed signature: 5eca6e0e015e95007aea73c2c56fa35d
// flow-typed version: <<STUB>>/passport-strategy_v1.0.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'passport-strategy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'passport-strategy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'passport-strategy/lib/index' {
  declare module.exports: any;
}

declare module 'passport-strategy/lib/strategy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'passport-strategy/lib/index.js' {
  declare module.exports: $Exports<'passport-strategy/lib/index'>;
}
declare module 'passport-strategy/lib/strategy.js' {
  declare module.exports: $Exports<'passport-strategy/lib/strategy'>;
}
